### ISSUE TITLE
Move this repo to ipfs-primer and re-name the book to IPFS Primer

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs-shipyard/ipfs-primer#42]
Following up from Issue #10, and in order to allow contributors like @edgo914, @art-blocksec, @macabeus, @chadoh, @jcea, etc to move forward, I'd like to rename this repo to ipfs-primer and change the title of the primer to IPFS Primer. I'd also like to add @edgo914 and anyone else who's interested as maintainers of the repo. This would move all the issues, PRs, etc to that new location and let everyone use that info to keep building an IPFS primer. 

Meanwhile, I will reboot the repo at flyingzumwalt/decentralized-web-primer with the content that's been in the [`reboot` branch](https://github.com/flyingzumwalt/decentralized-web-primer/tree/reboot) since early 2019. That content speaks to the broader topic of building a Decentralized Web rather than focusing on providing a primer on using IPFS. I think both of those primers should exist, but my interest these days lies in speaking to the fundamentals of decentralized networks rather than any specific technology. My change in interest shouldn't block other people from making a great reference document for IPFS users. 

Could I get a confirmation that people agree with this course of action before I make such big changes? I know @edgo914 has especially done a lot of work in their own fork at https://github.com/edgo914/decentralized-web-primer/  so I'm especially interested in hearing from them before proceeding.

**Comment by edgo914** [comment]
Hey Matt!

I don't mind if you rename it, kinda makes more sense. So then you would
pull all of my work into it before the rename? I'm fine with being a
maintainer.

Ed

**Comment by jessicaschilling** [comment]
@flyingzumwalt -- thanks for opening up this discussion! I'm going to cc in @johnnymatthews, since he's the grandmaster of IPFS documentation, and I'm sure will have some valuable thoughts. (That might include whether it makes sense at all to bring the content itself somewhere into the IPFS org, though perhaps that feels too centralized?)

**Comment by flyingzumwalt** [comment]
@edgo914 I think the forks will still work after the rename. Let's test it with yours. I'm going to try renaming it now. If the rename breaks the connection with all the forks, I will change it back and we might have to rethink this, since 27 people have made forks. 

@johnnymatthews do you think we should move it from flyingzumwalt to the ipfs-shipyard org?

**Comment by flyingzumwalt** [comment]
It looks like the forks stayed intact through the rename. I will wait a few days for the dust to settle before I create another repo at the old URL (until then, github will automatically redirect people to the new URL)

**Comment by jessicaschilling** [comment]
@flyingzumwalt @johnnymatthews - FWIW, I think ipfs-shipyard is a *great* idea.

**Comment by flyingzumwalt** [comment]
@edgo914 you're a collaborator now. After you've applied your changes, please merge #43 so all the URL references stay valid.

**Comment by edgo914** [comment]
OK folks, I've applied all my changes and new content to
https://github.com/flyingzumwalt/ipfs-primer :-)

Matt, wasn't sure about the merge #43 step, seems like URL references are
good

https://flyingzumwalt.gitbooks.io/decentralized-web-primer/ ... new content
shows up here now, I think you would need to change URL to /ipfs-primer/

Or not, this seems to link fine from frontpage of https://ipfs.io/

**Comment by johnnymatthews** [comment]
Sorry for the delay in getting over here! I've been buried in post-holiday emails. Shipyard is the perfect place for this project is land. I'll find out the process for getting this moved over there.

**Comment by flyingzumwalt** [comment]
@johnnymatthews if you can confirm that it should be moved to the shipyard I can move it.

**Comment by flyingzumwalt** [comment]
I spoke with @jessicaschilling, who confirmed that this move already has approval from the shipyard maintainers. Moved the repo to the shipyard, updated all the references and merged PR #43. That closes out the work to be done on this issue!

**Comment by jessicaschilling** [comment]
Awesome - I'll also update where this is linked to from the IPFS docs beta.
