### ISSUE TITLE
Post the rendered primer somewhere so people can view/download it!

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs-shipyard/ipfs-primer#44]
Before being moved to ipfs-shipyard, this primer was being rendered and posted at https://dweb-primer.ipfs.io, presumably by some CI process. I'm pretty sure that won't get updated any more. It was also rendering to https://flyingzumwalt.gitbooks.io/decentralized-web-primer/content/, a location that I'm going to re-use for new dweb primer content.

Steps to take: 

- [ ] Set up a CI workflow, or some other process to render the book and post it as a website that people can view.
- [ ] Make sure people can also download the pdf, mobi, and kindle versions
- [ ] update any associated links to point to the right place, so people can find it!

**Comment by edgo914** [comment]
This is live now at https://ipfs.io/
Scroll down to "What do you want to do with IPFS?" ... Manage large amounts
of data (click to open) ... "Learn the key principles" link

But yes of course it will change if you modify
https://flyingzumwalt.gitbooks.io/decentralized-web-primer/

**Comment by flyingzumwalt** [comment]
I will be modifying what appears at https://flyingzumwalt.gitbooks.io/decentralized-web-primer/ to show the content that was in the "reboot" branch. Anything that renders from my repo at flyingzumwalt/decentralized-web-primer will end up getting that new content, so if you want it to display the IPFS primer, it needs to get updated to render from ipfs-shipyard/ipfs-primer.

**Comment by edgo914** [comment]
Any idea who to contact regarding that switch? I'll work on that if I know
who ...

**Comment by flyingzumwalt** [comment]
I think @johnnymatthews might be a good person to start with.

**Comment by johnnymatthews** [comment]
Yeah I can make a PR into the `ipfs/website` repo if necessary. Is it just a case of changing a URL?

**Comment by flyingzumwalt** [comment]
This is not just a case of changing a URL. Someone needs to set up a way for this content to be re-rendered when it gets updated on github. 

- Option 1: Set up an account on gitbook.com and have that site render the content for you.
- Option 2: Set up a CI build, maintained by the IPFS infra team, that builds the content and publishes it to something within the ipfs.io domain.

Either way, once you have that set up you can then update the website(s) to point to whatever the new url is (ie. ipfs-shipyard.gitbook.com or ipfs-primer.ipfs.io or whatever)

I believe that the content at dweb-primer.ipfs.io is actually updated by a CI build that the IPFS infra team set up, not gitbook. If I remember correctly, the build actually renders the book and publishes it to IPFS using the same process that's used for the main ipfs.io website. The IPFS Infra team have probably updated their process since then, so you will have to ask them what to do.

**Comment by johnnymatthews** [comment]
Right I see! Sorry, misunderstood for a second there. The easiest option would be to throw the GitBook onto Netlify or somewhere like that, with an intention to move it over to IPFS in the future. I've contacted _infra_ to see what their preferred solution is.

**Comment by johnnymatthews** [comment]
After thinking about this for a few days, it'd make sense to merge this documentation into either [docs.ipfs.io](https://docs-beta.ipfs.io/) or [ProtoSchool](https://proto.school/#/) rather than having another separate resource to maintain. Thoughts @flyingzumwalt?

**Comment by flyingzumwalt** [comment]
I defer to you and others on answering that question. I haven’t worked on
this content since before protocol school was created. Much of this content
does seem somewhat redundant now, which is part of why I moved my attention
to other topics for dweb primer. I just want to make sure people who want
to do something with this content are able to move forward without being
blocked by needing some action from me. I don’t plan to work on it.

**Comment by johnnymatthews** [comment]
Right I see, that makes sense. In that case the best thing to do is to move the repo from this organization over to the `ipfs` organization. Then we can archive the repo but still keep it public so that anyone who does want use it still can. We can keep it around there for historical reasons, then after a couple years it's probably best to delete it.

**Comment by jessicaschilling** [comment]
Viewable at dweb-primer.ipfs.io.
